server:

  port: 12880
spring:
  application:
    name: qual
  profiles:
    active: uat
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.springboottest.entity
logging:
  level:
    com.example.springboottest.dao: debug



eureka:
  instance:
      # 配置使用指定IP
      #    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      # 优先使用IP地址方式进行注册服务
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    ip-address: 127.0.0.1
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://192.168.1.213:7300/eureka/


