server:
  port: 8080
spring:
  profiles:
      active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.springboottest.entity
logging:
  level:
    com.example.springboottest.dao: debug

