spring:

  datasource:
    username: xztollstation
    password: qwerty
    url: jdbc:oracle:thin:@192.168.0.200:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    # 数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 基本配置
      initial-size: 10
      max-active: 20
      min-idle: 10
      # 获取连接等待超时时间
      max-wait: 60000
      # 配置连接检测间隔时间，检测需要关闭的空连接
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生命时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL











